# Generated by Django 3.2.2 on 2021-05-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0002_alter_urlredirects_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlredirects',
            options={'verbose_name': 'URL Redirects'},
        ),
        migrations.AlterModelTable(
            name='urlredirects',
            table='Url',
        ),
    ]
