# Generated by Django 3.2.2 on 2021-05-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0003_auto_20210514_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlredirects',
            options={'verbose_name': 'URL Redirect'},
        ),
        migrations.AlterModelTable(
            name='urlredirects',
            table='redirector',
        ),
    ]
